kind: pipeline
name: build arm64

platform:
  os: linux
  arch: arm64
  
node:
  city: sydney

trigger:
  event:
    include:
    - custom
steps:
- name: build operator
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    IMAGE_REGISTRY:
      from_secret: image_registry
    IMAGE_NAMESPACE:
      from_secret: image_namespace
    IMAGE_NAME:
      from_secret: image_name
    IMAGE_TAG:
      from_secret: image_tag
    GOOS: linux
    GOARCH: arm64
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $IMAGE_REGISTRY
  - docker build --build-arg ARCH=$GOARCH -t $IMAGE_REGISTRY/$IMAGE_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG .
  - docker push $IMAGE_REGISTRY/$IMAGE_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG
  when:
    event:
      include:
      - custom
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock